name: Update README
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Fetch feeds
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gautamkrishnar/blog-post-workflow@v1
      with:
        comment_tag_name: BLOG
        feed_list: https://arnaudligny.fr/blog/atom.xml
        max_post_count: 4
    - uses: gautamkrishnar/blog-post-workflow@v1
      with:
        comment_tag_name: PODCAST
        feed_list: https://anchor.fm/s/39f4fa04/podcast/rss
