name: Workflow
on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch: 
jobs:
  update-readme-with-episodes:
    name: Update README
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: BLOG
          feed_list: "https://arnaudligny.fr/atom.xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: PODCAST
          feed_list: "https://anchor.fm/s/39f4fa04/podcast/rss"
